#ifndef SAP_VM_CONFIG_H
#define SAP_VM_CONFIG_H

#define MEMORY_SIZE 1024
#define STACK_TOP (MEMORY_SIZE - 1)
#define PROGRAM_START 0
#define MAX_BREAKPOINTS 32
#define MAX_INPUT_SIZE 256
#define MAX_COMMAND_SIZE 32
#define MAX_ARGS_SIZE 224
#define DATA_MEMORY_START 0x100
#define SUBROUTINE_START 0x10

#endif // SAP_VM_CONFIG_H

